import { createUniqueId } from "solid-js";



export class TodoItem extends OfficeItem {
  /**
   * Generic class defining the TodoItem, which represents individual to-dos the user adds to their to-do list.
   *
   *
   * @param id - an autogenerated id, read but not written to when initializing a new to-do
   * @param name - the user-provided title of the to-do
   * @param details - the user-provided body text of the to-do
   * @param attachments - any attachments the user had added onto the to-do provided as
   *
   */

  constructor(
    data: {
      name: string;
      details?: string;
      attachments?: string;
      date?: {
        start?: string;
        end?: string;
      };
    },
  ) {
    super();
  }
}

export class TodoList extends OfficeCollection<TodoItem> {
  constructor(
    todo_items: TodoItem[],
    meta: {
      created_at: Date;
      access: AccessManager;
    }
  ) {}
}

export class Notifier {}








let hello = new TodoItem();
